---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Gather package facts
      ansible.builtin.package_facts:
    - name: Check if sysbox is installed
      ansible.builtin.assert:
        that: "'sysbox-ce' in ansible_facts.packages"
    - name: Check if sysbox version is correct
      ansible.builtin.assert:
        that: >
          ansible_facts.packages['sysbox-ce'][0].version | regex_search('^(\\d|[1-9]\\d)\\.(\\d|[1-9]\\d)\\.(\\d|[1-9]\\d)')
          == '0.5.0'
